version: "3.8" # latest version of Dockerfile
services:
 anandjavaapp1: # name of application 
  image: tomcat  # the same image we build in build step 
  container_name: anandjavac1
  ports:
  - "5501:8080"
  volumes:
  - "./jspapp-master/target:/usr/local/tomcat/webapps/"
  
